server:
  port: 12306

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://212.129.252.199:3306/words
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug