server:
  port: 8080

spring:
  datasource:
    username: root
    password: otvo0620
    url: jdbc:mysql://localhost:3306/word
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug