server:
  port: 12306

spring:
  datasource:
    username: words
    password: 123456
    url: jdbc:mysql://124.220.22.177:3306/words
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug